import type { Metadata } from "next";
import { AppShell, Header } from "@/components/app";
import { ReactQueryProvider } from "@/components/app/query-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <ReactQueryProvider>
          <AppShell header={<Header title="Performance Comparison" />}>
            {children}
          </AppShell>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
